export const ENDPOINTS = {
  appInit: '/app-init',
  media: {
    list:             '/media',
    detail:           (id: number) => `/media/${id}`,
    words:            (id: number) => `/media/${id}/words`,
    continueLearning: '/media/continue-learning',
    seriesEpisodes:   (imdbId: string) => `/media/series/${imdbId}/episodes`,
    watchToggle:      (id: number) => `/media/${id}/watch`,
    watchedIds:       '/media/watched-ids',
  },
  words: {
    search:         '/words/search',
    frequent:       '/words/frequent',
    detail:         (id: number) => `/words/${id}`,
    markKnown:      (id: number) => `/words/${id}/mark-known`,
    markKnownBatch: '/words/mark-known/batch',
    note:           (id: number) => `/words/${id}/note`,
  },
  user: {
    stats:           '/user/statistics',
    knownWords:      '/user/known-words',
    deviceToken:     '/user/device-token',
    notifications:   '/user/notifications',
    notifUnread:     '/user/notifications/unread-count',
    notifMarkRead:   '/user/notifications/mark-read',
    notifPushToggle: '/user/notifications/push-enabled',
  },
  lists: {
    list:               '/lists',
    standard:           '/lists/standard',
    bySeries:           (imdbId: string) => `/lists/media/imdb/${imdbId}`,
    detail:             (id: number) => `/lists/${id}`,
    update:             (id: number) => `/lists/${id}`,
    words:              (id: number) => `/lists/${id}/words`,
    wordItem:           (listId: number, wordId: number) => `/lists/${listId}/words/${wordId}`,
    generateFromMedia:  '/lists/generate/unknown',
    generateSubList:    (id: number) => `/lists/${id}/generate/unknown`,
    containingWord:     (wordId: number) => `/lists/containing-word/${wordId}`,
  },
  auth: {
    login:          '/auth/login',
    register:       '/auth/register',
    deleteAccount:  '/auth/account',
    forgotPassword: '/auth/forgot-password',
    resetPassword:  '/auth/reset-password',
  },
  subscription: {
    me: '/subscription/me',
  },
  study: {
    nextBatch: '/study/next-batch',
    result:    '/study/result',
  },
  progress: {
    stats:     '/progress/stats',
    difficult: '/progress/words/difficult',
    learnt:    '/progress/words/learnt',
    studied:   '/progress/words/studied',
    due:       '/progress/words/due',
    notes:     '/progress/words/notes',
  },
} as const;
